---
  - name: Install OpenMRS
    become: yes
    hosts: all
    vars:
      - odoo_git_repo_path: https://github.com/odoo/odoo.git 
    tasks:
      - name: update apt repo and cache
        apt:
          update_cache: yes

      - name: Clone a odoo repository
        ansible.builtin.git:
          repo: "{{ odoo_git_repo_path }}"
          dest: /home/devops/odoo
          clone: yes
          update: no

      - name: Install pip3,postgresql and postgresql-client
        ansible.builtin.apt:
          name: "{{ item }}"
          state: present
        with_items:
          - python3-pip
          - postgresql
          - postgresql-client

     # - name: create a db user
       # postgresql_user:
        #  state: present
         # name: devops
         # password: devops
         # role_attr_flags: SUPERUSER
        #ignore_errors: True

     # - name: create database
      #  postgresql_db:
       #   state: present
       #   name: devops
       # ignore_errors: True

      - name: create a new PostgreSQL user
        ansible.builtin.command:
          cmd: sudo -u postgres createuser -s $USER
        ignore_errors: True

      - name: create database
        ansible.builtin.command:
          cmd: createdb $USER
        ignore_errors: True


      - name: Install dependencies for PostgreSQL
        apt: 
          name: "{{ item }}"
          update_cache: true 
          state: latest
        with_items:
          - python3-dev
          - libxml2-dev
          - libxslt1-dev
          - libldap2-dev
          - libsasl2-dev
          - libtiff5-dev
          - libjpeg8-dev
          - libopenjp2-7-dev
          - zlib1g-dev
          - libfreetype6-dev
          - liblcms2-dev
          - libwebp-dev
          - libharfbuzz-dev
          - libfribidi-dev
          - libxcb1-dev
          - libpq-dev

      - name: Install setuptools, wheel python package
        pip:
          name:
            - setuptools
            - wheel
          chdir: /home/devops/odoo

      - name: Install pythone requiremetns
        pip:
          requirements: /home/devops/odoo/requirements.txt

      - name: Install nodejs and npm
        ansible.builtin.apt:
          name: "{{ item }}"
          state: present
        with_items:
          - nodejs
          - npm

      - name: executing odoo
        ansible.builtin.command:
          cmd: sudo python3 odoo-bin --addons-path=addons -d mydb

      