---
- name: Installing mysql 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
       - mysql-server
       - python3-pymysql

- name: checking the plugin for root
  ansible.builtin.shell:
    cmd: mysql -Nse "select count(*) from mysql.user where user = 'root' and authentication_string is null"
  ignore_errors: yes
  register: root_password

- name: print rootpassword
  ansible.builtin.debug:
    var: root_password.stdout
    
- name: Change the authentication plugin of MySQL root user to mysql_native_password
  ansible.builtin.shell:
    cmd: mysql -Nse 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
  ignore_errors: yes

- name: Set MySQL root Password
  mysql_user:
    check_implicit_admin: yes
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: 'root'
    state: present
  ignore_errors: yes
  notify:
        - Restart mysql
  
- name: Flush Privileges
  ansible.builtin.shell:
    cmd: mysql -u root -e 'FLUSH PRIVILEGES'
  ignore_errors: yes
  notify:
        - Restart mysql

- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: root
    name: spurtcommerce
    state: present

- name: Copy database dump file to remote host and restore it to database 'my_db'
  mysql_db: 
    name: spurtcommerce 
    state: import 
    target: /home/devops/Spurtcommerce_3.0.2_community_LTS/spurtcommerce.sql


  
    