---
- name: Installing mysql 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
       - mysql-server
       - python3-pymysql

- name: Set MySQL root Password
  mysql_user:
    check_implicit_admin: yes
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: 'root'
    state: present
  ignore_errors: yes
  notify:
        - Restart mysql
  
- name: Flush Privileges
  ansible.builtin.shell:
    cmd: mysql -u root -e 'FLUSH PRIVILEGES'
  ignore_errors: yes
  notify:
        - Restart mysql

- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: root
    name: spurtcommerce
    state: present



  
    