---
- name: Install packages based on package.json.
  community.general.npm:
    path: "{{ spurtcommerce_store_path }}"

- name: Change the working directory to api path, build the project
  ansible.builtin.command: npm run build
  args:
    chdir: "{{ spurtcommerce_store_path }}"

- name: Copy all files from dist folder to the server apache path
  ansible.builtin.copy:
    src: "{{ spurtcommerce_store_path }}"
    dest: "{{ apache_path }}"
    owner: devops
    group: devops
    mode: '0655'

- name: Start the project
  ansible.builtin.command: npm start serve
  args:
    chdir: "{{ spurtcommerce_api_path }}"