---
- name: Installing mysql 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
       - mysql-server
       - python3-pymysql

- name: start and enable mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  
- name: Set MySQL root Password
  mysql_user:
    check_implicit_admin: yes
    login_host: 'localhost'
    login_user: 'root'
    login_password: 'root'
    name: 'root'
    password: 'root'
    state: present
  ignore_errors: yes
  notify:
        - Restart mysql
  
- name: Flush Privileges
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
       - sudo mysql -uroot -proot
       - '-e FLUSH PRIVILEGES;'  
  notify:
        - Restart mysql
    

- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: root
    name: spurtcommerce
    state: present

- name: Copy database spurtcommerce sql database file to spurtcommerce databse
  community.mysql.mysql_db: 
    name: spurtcommerce 
    state: import 
    target: /home/devops/Spurtcommerce_3.0.2_community_LTS/spurtcommerce.sql
    login_user: root
    login_password: root
    force: yes


  
    