---
- name: Download nopCommerce
  ansible.builtin.get_url:
    url: "https://github.com/pixelswapnil13/Ansible/raw/main/spurtcommerce/Spurtcommerce_3.0.2_community_LTS.zip"
    dest: "{{ spurtcommerce_download_location }}"
    mode: '0777'

- name: Install Unzip
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Unarchive Spurtcommerce_3.0.2_community_LTS.zip
  ansible.builtin.unarchive:
    src: "{{ spurtcommerce_download_location }}/Spurtcommerce_3.0.2_community_LTS.zip"
    dest: "{{ spurtcommerce_download_location }}"
    remote_src: yes
    owner: devops
    group: devops

- name: update db password in env file
  ansible.builtin.command:
    cmd: sed -i 's/TYPEORM_PASSWORD=PASSWORD/TYPEORM_PASSWORD=root/g' /home/devops/Spurtcommerce_3.0.2_community_LTS/api/.env

- name: update db name in env file
  ansible.builtin.command:
    cmd: sed -i 's/TYPEORM_DATABASE=DATABASE/TYPEORM_DATABASE=spurtcommerce/g' /home/devops/Spurtcommerce_3.0.2_community_LTS/api/.env

- name: update bcrypt version to 5.0.1
  ansible.builtin.command:
    cmd: "sed -i 's/{{ bcrypt_old_version }}/{{ bcrypt_new_version }}/g' /home/devops/Spurtcommerce_3.0.2_community_LTS/api/package.json"

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/devops/Spurtcommerce_3.0.2_community_LTS/api

- name: Install typeorm-seeding@1.0.0-beta.6
  npm:
    name: "typeorm-seeding"
    path: /home/devops/Spurtcommerce_3.0.2_community_LTS/api/node_modules/
    version: '1.0.0-beta.6'

#- name: Changig directory to api
 # command: 
  #  cmd: "cd {{ spurtcommerce_api_path }}"

#- name: Build app
 # command: 
  #  cmd: npm run build

- name: Change the working directory to somedir/ and run the command as db_owner if /path/to/database does not exist
  ansible.builtin.command: npm run build
  args:
    chdir: "{{ spurtcommerce_api_path }}"