---
- name: Ensure apache2 service is restarted
  ansible.builtin.service:
    name: apache2
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Restart mysql
  ansible.builtin.systemd:
    name: 'mysql.service'
    daemon_reload: yes
    enabled: yes
    state: restarted
